# Generated by Django 5.2.6 on 2025-11-26 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('price', models.FloatField(blank=True, null=True)),
                ('power_reserve', models.CharField(blank=True, max_length=144, null=True, verbose_name='Запас хода')),
                ('overclocking', models.CharField(blank=True, max_length=144, null=True, verbose_name='Разгон')),
                ('charging_time', models.CharField(blank=True, max_length=144, null=True, verbose_name='Время зарядки')),
                ('ground_clearance', models.CharField(blank=True, max_length=144, null=True, verbose_name='Дорожный просвет')),
                ('charging_speeds', models.CharField(blank=True, max_length=144, null=True, verbose_name='Скорость зарядки')),
                ('hybrid_motor', models.CharField(blank=True, max_length=144, null=True, verbose_name='Гибридный мотор')),
            ],
        ),
        migrations.CreateModel(
            name='InteriorFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/products/interior_features')),
                ('description', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='block_products.products')),
            ],
        ),
        migrations.CreateModel(
            name='InteriorColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_color_user', models.CharField(max_length=155)),
                ('name_color', models.CharField(max_length=155)),
                ('hex', models.CharField(max_length=12)),
                ('image_preview', models.ImageField(upload_to='images/products/interior_color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='block_products.products')),
            ],
        ),
        migrations.CreateModel(
            name='ExteriorFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/products/exterior_features')),
                ('description', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='block_products.products')),
            ],
        ),
        migrations.CreateModel(
            name='DescriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_description', models.CharField(max_length=255)),
                ('text_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/products/description_model')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='block_products.products')),
            ],
        ),
        migrations.CreateModel(
            name='BodyColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_color_user', models.CharField(max_length=155)),
                ('name_color', models.CharField(max_length=155)),
                ('hex', models.CharField(max_length=12)),
                ('image_preview', models.ImageField(upload_to='images/products/body_color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='block_products.products')),
            ],
        ),
    ]
