# Generated by Django 5.2.6 on 2025-11-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default=1, upload_to='images/products/model'),
            preserve_default=False,
        ),
    ]
