# Generated by Django 5.2.6 on 2025-11-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_products', '0002_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='interiorcolor',
            name='hex_sub',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DescriptionModel',
        ),
    ]
