# Generated by Django 5.2.6 on 2025-12-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_products', '0004_alter_products_options_testdrive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdrive',
            name='phone_number_customer',
            field=models.CharField(max_length=13),
        ),
    ]
