# Generated by Django 5.2.6 on 2025-11-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_news', models.CharField(max_length=255)),
                ('slug_news', models.CharField(max_length=255)),
                ('main_image', models.ImageField(upload_to='images/news/main')),
                ('sub_image', models.ImageField(blank=True, null=True, upload_to='images/news/sub')),
                ('main_text', models.TextField()),
                ('sub_text', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
