# Generated by Django 5.2.6 on 2025-12-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
